### ISSUE TITLE
Navigation buttons no longer work!

### ISSUE THREAD

**Issue by just1ngray** [just1ngray/CSCI2356_AutismNS#10]
It seems the navigation buttons do not work in the current master branch. I suspect the <button> tag does not have a href="" attribute like the <a> tag did.

**Comment by just1ngray** [comment]
@VitorJeronimo , if I fix this, I'll just do it by turning it back to <a> tags. I assume you have a more accessible solution so I will let you do it!

**Comment by vbjeronimo** [comment]
It seems that the attribute "href" doesn't work on button tags, sorry about that. I've made some changes so not only will it work now, but it will also be easier to make changes in the future.
