### ISSUE TITLE
email.html "To" and "From" labels

### ISSUE THREAD

**Issue by vbjeronimo** [just1ngray/CSCI2356_AutismNS#14]
We have an issue with email.html. I can't apply a link to the correct help page without changing the JS code for loadMail(), because I need to refer to the label's id ("email_to_label", for example). Can we have two HTML documents for this section? One for Viewing Sent Item and another one for Viewing Inbox Item?

**Comment by just1ngray** [comment]
We don’t need two because the to/from label is currently being changed in the scripts/emailManager.js#loadMail method

Just use the id non_owner_type
See lines 324 and 341 in emailManager

**Comment by just1ngray** [comment]
Do we need help info on already sent items? I was thinking no, since there is nothing the user can do about the information they’re seeing

Help is important if the user is entering something. But getting help information about a proper subject line isn’t helpful if the subject can’t be changed

**Comment by just1ngray** [comment]
Realized the project guidelines require us to have these labels, good catch Vitor! We can use something like this for the help info:

![384A5A7B-9ECA-4B22-B849-F0F2837FBD32](https://user-images.githubusercontent.com/57203324/75700078-e45f1b80-5c87-11ea-8899-a3ac5807d24e.jpeg)
