### ISSUE TITLE
Admin - Student Storage

### ISSUE THREAD

**Issue by just1ngray** [just1ngray/CSCI2356_AutismNS#17]
I worked on hardcoding the admin and student systems. Currently, the localStorage is not shared between the admin and student directories. (You can check all the localStorage in your browser's inspector -- labelled Storage in Firefox.)

I have tried moving the homepage to the root folder with README.md and renaming student/admin/index.html to inbox.html, but this has not helped either.
I am stuck. Please help in the **hardcoded** branch. (Branch off hardcoded and if you find a solution just merge or overwrite hardcoded)

**Comment by vbjeronimo** [comment]
I'm checking the code right now and I don't understand what the problem is, everything seems to be working perfectly. Do you want to have the local storage shared between both directories?

**Comment by just1ngray** [comment]
Yes, the localstorage needs to be shared across the entire website (including subdirectories).
Is this not possible? It would suck to have all the files in the root folder but we might have to?

Otherwise the admin will never read emails sent from the student system

**Comment by vbjeronimo** [comment]
This is what I found:
    LocalStorage is domain-based. All pages with the same domain share single localStorage.
    Also to share localStorage, both pages need to have the same port and protocol like https.

Is it helpful in any way?

**Comment by just1ngray** [comment]
Is
file:///C:/Users/justi/Desktop/SMU/2-2/CSCI2356%20-%20Mobile%20App%20Dev/CSCI2356_AutismNS/student/compose.html
a different domain than
file:///C:/Users/justi/Desktop/SMU/2-2/CSCI2356%20-%20Mobile%20App%20Dev/CSCI2356_AutismNS/admin/inbox.html

It feels so messy to have two separate email systems and I am not sure how to organize it.

**Comment by vbjeronimo** [comment]
I don't think they have different domains. Let's take this website for example. github.com is the domain and everything that comes after it is just a URL. So it doesn't matter where you are on the website, you'll be always in the domain github.com.

The reason why I didn't understand the problem is that I sent an email to both accounts and it worked as it should for P1. Everybody gets the email, deleting the email in one account doesn't affect the other, and so on...

**Comment by just1ngray** [comment]
<img width="1635" alt="Capture" src="https://user-images.githubusercontent.com/57203324/75843366-5d09c900-5da9-11ea-8be7-24b8d2ce1d5b.PNG">

Left: Student
Right: Admin

I sent the mail and refreshed the page yet it did not show up in admin's inbox.

**Comment by vbjeronimo** [comment]
That's weird... It's working on my computer.

**Comment by just1ngray** [comment]
I just tried it in Chrome and it worked right away. Really odd...

**Comment by vbjeronimo** [comment]
Yeah, I wonder if we need to use a different code for it to work in Firefox... I think it was a good thing that we got this issue, now we can work on something to fix it before a user has a problem with it.
