### ISSUE TITLE
Sent Items can't be deleted

### ISSUE THREAD

**Issue by vbjeronimo** [just1ngray/CSCI2356_AutismNS#24]
I've just finished adding the review page to compose.html and while I was testing the program I realized that the emails on Sent Items are not being deleted. I also checked the master repository to see if it was a problem in my branch and it seems to have the same problem. No idea what's causing it, the Inbox is working just fine.

**Comment by just1ngray** [comment]
There was an error with a single email object being modified in two separate arrays. There are now two entirely different email objects.
Fixed woot woot
