### ISSUE TITLE
Long emails extend off the page

### ISSUE THREAD

**Issue by just1ngray** [just1ngray/CSCI2356_AutismNS#38]
When viewing a long email, line breaks and the end of the textarea element seem to go unrespected. I am not sure why this is. This has not been a problem until we started using the server. Can mongo not save line breaks?

`<div class="input-group-text">
      <label for="email_body" id="email_body_label" onclick='openHelp("email_body_label")'>Body</label>
      <span class="form-control viewEmailText" id="email_body"></span>
    </div>`

![image](https://user-images.githubusercontent.com/57203324/78802129-d2ae1980-7993-11ea-9e2f-6685a6f584d0.png)

**Comment by vbjeronimo** [comment]
Solved. The html element for the email body should be a textarea with the readonly attribute.
