### ISSUE TITLE
Checkbox aligned too high

### ISSUE THREAD

**Issue by just1ngray** [just1ngray/CSCI2356_AutismNS#39]
I'm not sure how to align the checkbox lower. You can add some class="xxxxx" on line 110 of emailManager.js. But I do not know which class to apply to get it aligned perfectly...

**Comment by vbjeronimo** [comment]
The problem was in the Bootstrap class (form-check-input). Bootstrap defined the position of the element as "absolute", so it kinda doesn't follow the rules of its parent div, so I've just overridden the position in our CSS file to "relative".
