### ISSUE TITLE
Server Documentation

### ISSUE THREAD

**Issue by vbjeronimo** [just1ngray/CSCI2356_AutismNS#40]
Hey Justin! I finished checking all the documentation, but I didn't write a description for the server and for the last two functions on the server file. Would you mind writing something there? 

Also, I believe that the project is good to submit! I gave it a test but let me know if you find something is weird.

Cheers!

**Comment by vbjeronimo** [comment]
Also, I changed the Port to 3384, because for some reason Port 3355 is still blocked for me and I couldn't test the program without changing it. So feel free to change it if you want.

**Comment by just1ngray** [comment]
I noticed port 3384 worked great! No need to change it! I will write some documentation for the mentioned files and give it a final test. It looks great!

________________________________
