### ISSUE TITLE
Script tags in index.html

### ISSUE THREAD

**Issue by vbjeronimo** [just1ngray/CSCI2356_AutismNS#7]
We need to organize the code in index.html to get rid of the script tags in the middle of the code. Do these functions run when the page is loaded? If they are, we can simplify it by using the attribute "onload".

**Comment by just1ngray** [comment]
Is having the script tags in the middle of the structure bad form? We can simply move them to the bottom of the page like you did in compose.html!

**Comment by JayPatel200** [comment]
I agree with Justin about this one(script tags). And I think that the function should run after the page is loaded as it is using the ID as a parameter. But we can move the script tag to the end to make it organized.
